services:
    db:
        image: mariadb:11
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MARIADB_USER: example
            MARIADB_PASSWORD: secret
            MARIADB_DATABASE: example
            MARIADB_ROOT_PASSWORD: secret
        restart: unless-stopped

    phpmyadmin:
        image: phpmyadmin:latest
        environment:
            PMA_ARBITRARY: true
            PMA_HOST: db
            UPLOAD_LIMIT: 10M
        networks:
            - default
            - traefik
        restart: unless-stopped
        ports:
        - "8080:80"

volumes:
    db-data:

networks:
    traefik:
        external: true
